store/carts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.my_cart, name='my_cart'),
    url(r'^remove/(?P<cart_item_id>[\d]+)/$', views.remove_item, name='remove_item'),
]

store/onlinestore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^', include('products.urls')),
    url(r'^account/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^mycart/', include('carts.urls')),
    url(r'^orders/', include('orders.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^shipping/', include('shipping.urls')),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}), 
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': settings.DEBUG}), 
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/products/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.all_products, name='all_products'),
    url(r'^search/', views.search_products, name='search_products'),
    url(r'^product/(?P<slug>[\w-]+)/$', views.single_product, name='single_product'),
]

store/products/models.py
from django.core.urlresolvers import reverse
from django_extensions.db.fields import AutoSlugField
from django.db import models

class Product(models.Model):
	slug = AutoSlugField(('slug'), max_length=60, unique=True, populate_from=('title',))
	title = models.CharField(max_length=50)
	description = models.TextField()
	price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
	sale_price = models.DecimalField(decimal_places=2, max_digits=100,\
												null=True, blank=True)
	active = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title

class ProductImage(models.Model):
	product = models.ForeignKey(Product)
	image = models.ImageField(upload_to='products/images/')
	active = models.BooleanField(default=True)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __str__(self):
		return "<Image: %d - %s>" % (self.id, self.product.title)

class VariationManager(models.Manager):
	def all(self):
		return super(VariationManager, self).filter(active=True)

	def sizes(self):
		return self.all().filter(category='size').filter(active=True)

	def colors(self):
		return self.all().filter(category='color').filter(active=True)

VAR_CATEGORIES = (
	('color', 'color'),
	('size', 'size'),
	)

class ProductVariation(models.Model):
	product = models.ForeignKey(Product)
	category = models.CharField(max_length=120, choices=VAR_CATEGORIES, default='color')
	title = models.CharField(max_length=120)
	image = models.ForeignKey(ProductImage, null=True, blank=True)
	price = models.DecimalField(max_digits=100, decimal_places=2, null=True, blank=True)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default=True)
	length = models.IntegerField(null=False)
	width = models.IntegerField(null=False)
	height = models.IntegerField(null=False)
	objects = VariationManager()

	def __str__(self):
		return self.title

store/products/views.py
from django.shortcuts import render
from django.db.models import Q

from .models import Product

def all_products(request):
	products = Product.objects.all()
	context = {"products": products}
	return render(request, 'products/all.html', context)

def single_product(request, slug):
	product = Product.objects.get(slug=slug)
	context = {"product": product}
	return render(request, 'products/single.html', context)

def search_products(request):
	search_term = request.GET.get('term')
	search_results = Product.objects.filter(
					Q(title__icontains=search_term) |
					Q(description__icontains=search_term)
				)
	context = {"products": search_results,
			   "search_term": search_term}
	return render(request, 'products/all.html', context)

store/products/templates/products/all.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
	{% if search_term %}
		{% include 'breadcrumbs.html' %}
		<h2><strong>&#34;{{ search_term }}&#34;</strong>的搜索结果</h2>
	{% endif %}

	{% if products %}

		{% for product in products %}
		  <div class="col-sm-6 col-md-4">
		    <div class="thumbnail">
		      <img src="{{ MEDIA_URL }}{{ product.productimage_set.first.image }}" alt="{{ product.title }}"/>
		      <div class="caption text-center">
		        <h3>{{ product.title }}</h3>
		        <p>{{ product.description }}</p>
				<a href='{% url "single_product" product.slug %}' class="btn btn-default" role="button">产品明细</a>
		      </div>
		    </div>
		  </div>

		{% endfor %}

	{% else %}

		{% if search_term %}
			<p>度不起，搜不到你想要的东西。</p>
		{% else %}
			<p>No prodcts have been listed in this store.</p>
		{% endif %}

	{% endif %}

{% endblock %}

store/products/templates/products/single.html
{% extends 'base.html' %}

{% block content %}

{% include 'breadcrumbs.html' %}

<div class="row">
	<div class="col-xs-12 col-sm-3">
		<div class="thumbnail">
			<img src="{{ MEDIA_URL }}{{ product.productimage_set.first.image }}" alt="{{ product.title }}"/
>		</div>
		<div class="caption text-center">
			<form method="POST" action='{% url "my_cart" %}'>
				{% csrf_token %}
				<input type="hidden" name="product" value={{ product.slug }} />

			 	{% if product.productvariation_set.all %}

				 	{% if product.productvariation_set.sizes %}
				 	<select class='form-control' name='size'>
				 	{% for item in product.productvariation_set.sizes %}
				 		<option value='{{ item.id }}'>{{ item.title }}</option>
				 		{% endfor %}
				 	</select>
				 	{% endif %}

				 	 {% if product.productvariation_set.colors %}
				 	<select class='form-control' name='color'>
				 	{% for item in product.productvariation_set.colors %}
				 		<option value='{{ item.id }}'>{{ item.title }}</option>
				 		{% endfor %}
				 	</select>
				 	{% endif %}

			 	{% endif %}

				<input type="number" min="1" max="9" value="1" name="quantity" class="form-control">
				<br>
				<button type="submit" class="btn btn-success">加入购物车</button>
			</form>
		</div>		
	</div>
	<div class="col-xs-12 col-sm-9">
		<h3>{{ product.title }}</h3>
		<p><span class="glyphicon glyphicon-usd">{{ product.price }}</span></p>
		<p>{{ product.description }}</p>
	</div>
</div>

{% endblock %}